# Generated by Django 3.2 on 2021-06-15 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('matricula', models.CharField(default=None, max_length=6, primary_key=True, serialize=False)),
                ('modelo', models.CharField(default=None, max_length=30)),
                ('horas_vuelo', models.IntegerField(default=0)),
                ('fecha_inspeccion_anual', models.DateField()),
                ('fecha_aeronavegabilidad', models.DateField()),
                ('ano_fabricacion', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Aeronave',
                'ordering': ['matricula'],
            },
        ),
        migrations.CreateModel(
            name='Consutor',
            fields=[
                ('rut', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('rut', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=200)),
                ('apellido', models.CharField(default=None, max_length=200)),
                ('horas_vuelo_A', models.CharField(default=0, max_length=1000)),
                ('horas_vuelos_E', models.CharField(default=0, max_length=1000)),
                ('licencia_vencida', models.BooleanField(default=False)),
                ('password', models.CharField(default=None, max_length=250)),
            ],
            options={
                'db_table': 'piloto',
                'ordering': ['rut'],
            },
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_vuelo', models.CharField(default=None, max_length=30)),
                ('duracion_vuelo', models.IntegerField(default=0)),
                ('origen', models.CharField(default=None, max_length=250)),
                ('destino', models.CharField(default=None, max_length=250)),
                ('mision_completada', models.BooleanField(default=False)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.aeronave')),
                ('copiloto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='copiloto', to='apirest.piloto')),
                ('piloto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='piloto', to='apirest.piloto')),
            ],
            options={
                'db_table': 'vuelos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipalidad', models.CharField(default=None, max_length=100)),
                ('direccion', models.CharField(default=None, max_length=100)),
                ('clase', models.CharField(default=None, max_length=1)),
                ('fecha_ultimo_control', models.DateField()),
                ('fecha_control', models.DateField()),
                ('n_licencia_piloto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_licencia', to='apirest.piloto')),
            ],
            options={
                'db_table': 'Licencia',
                'ordering': ['n_licencia_piloto'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_componente', models.CharField(default=None, max_length=200)),
                ('tipo', models.CharField(default=None, max_length=30)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apirest.aeronave')),
            ],
            options={
                'db_table': 'Componente',
                'ordering': ['id'],
            },
        ),
    ]
