# Generated by Django 3.2 on 2021-06-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='duracion_vuelo',
            new_name='duracion_vuelo_c',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='duracion_vuelo_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='duracion_vuelo_total',
            field=models.IntegerField(default=0),
        ),
    ]
