# Generated by Django 3.2 on 2021-06-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_auto_20210615_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consutor',
            new_name='Consultor',
        ),
    ]
