# Generated by Django 3.2 on 2021-06-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_rename_consutor_consultor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultor',
            name='apellido',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='consultor',
            name='nombre',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
