# Generated by Django 3.2 on 2021-06-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_auto_20210616_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultor',
            options={'ordering': ['rut']},
        ),
        migrations.AlterModelTable(
            name='consultor',
            table='consultor',
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantencion', models.DateField()),
                ('detalle_mantencion', models.CharField(default=None, max_length=300)),
                ('encargado_mantenimiento', models.CharField(default=None, max_length=250)),
                ('horas_vuelo', models.IntegerField(default=0)),
                ('aeronave', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reporte', to='apirest.aeronave')),
            ],
        ),
    ]
