# Generated by Django 3.2 on 2021-06-17 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_auto_20210617_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='reportes',
        ),
    ]
