# Generated by Django 3.2 on 2021-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0006_auto_20210617_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='fecha_mantencion',
            field=models.DateField(default=None),
        ),
    ]
